# -*- coding: utf-8 -*-
"""
/***************************************************************************
 3DToolbox
                                 A QGIS plugin
 This plugin provides tools and functions for 3D geometries and volumes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-08-11
        copyright            : (C) 2021 by 3D geoinformation group
        email                : steliosvitalis@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = '3D geoinformation group'
__date__ = '2021-08-11'
__copyright__ = '(C) 2021 by 3D geoinformation group'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load 3DToolbox class from file 3DToolbox.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .three_toolbox import ThreeToolboxPlugin
    return ThreeToolboxPlugin()
